# Generated by Django 5.0 on 2023-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwork', '0002_note_mod_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
